plugins:
  - jekyll-remote-theme
remote_theme: zivong/ockham

markdown: CommonMarkGhPages
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

baseurl: /
title: keymoon's note
tagline: Writeup とか、あわよくば解説記事とか
description: 説明ってどこに表示されるんですか?
author:
  name: keymoon
  url: https://twitter.com/kymn_
disqus: keymoon-writeup
